### ISSUE TITLE
verify file/folders containing "\#"

### ISSUE THREAD

**Issue by inmarelibero** [inmarelibero/gitignore-checker#3]
"#" character contained in file or folder names could give problems with `preg_match()` delimiters: check it out

**Comment by dimabory** [comment]
Could you please explain what is the major issue with "#" character and provide some use cases?

I also suggest creating a checklist of special cases (might be great to adopt from here https://git-scm.com/docs/gitignore#_pattern_format)

**Comment by dimabory** [comment]
Oh, I found the useful link in your code

Let me put it here https://labs.consol.de/development/git/2017/02/22/gitignore.html

**Comment by inmarelibero** [comment]
@dimabory major issue I can see comes from `preg_match()` usage: as you can see here https://github.com/inmarelibero/gitignore-checker/blob/master/src/Utils/StringUtils.php#L82:

```
$regex = sprintf('#%s#i', $regex);
return preg_match($regex, $input) === 1;
```

a rule representing a single `.gitignore` row is:
- read from `.gitignore` (eg. `/README`, `/.*md`, `/foo`, etc..)
- then surrounded with delimiters `#`, as `preg_match()` first argument requires
- then `preg_match()` is executed

problem that can arise is that if, for example, read rule is `\#foo`, the execution of `preg_match("#\#foo#")` should give problems, as the character chosen as delimiter, afaik, cannot be used inside the regex

I haven't tried yet, because I've never see any `.gitignore` containing `\#` in rules, but indeed must be supported by this library, as exists as specification.

The most important tests are performed here: https://github.com/inmarelibero/gitignore-checker/blob/master/tests/Utils/PathUtilsTest.php: here is where, in my intentions, all rules are added in order to guarantee that this library works well

ps: I'de be pleased to have some contributions, even if I've been working a long with PHP, this is my first serious open source library
also, this project is related to this issue https://github.com/symfony/symfony/issues/26714#issuecomment-469634733, but it will have a stand alone life anyway

**Comment by dimabory** [comment]
Nice, I found this repo due to the comment in symfony issues.

Could you please explain why do you use `preg_match("#\#foo#")` instead of `preg_match("/\#foo/")`?

**Comment by inmarelibero** [comment]
because `/` would give a lot of more severe problems, as `/` is the delimiter for subfolders and it's far more common to find it in `.gitignore` files

my steps would be:
- first of all verify if `\#` really would give problems
- if it is so, try to:
    1) use `#` as delimiter if `#` is not present the rule
    1) use `@` as delimiter if `@` is not present the rule

of course this solution would crack if you use `@` in the `.gitignore` file, so I would look for a kind of "universal" delimiter, a character that can't be used in a `.gitignore`

**Comment by inmarelibero** [comment]
I was also looking at:

   Assertion::regex(mixed $value, string $pattern);

in  `beberlei/assert` package -> https://github.com/beberlei/assert

**Comment by dimabory** [comment]
I'm not sure it's a good idea to throw an exception if `.gitignore` contains empty lines or comment (https://github.com/inmarelibero/gitignore-checker/blob/master/src/Model/GitIgnoreRule.php#L47). It would be better just skip those lines and don't take into account.

**Comment by inmarelibero** [comment]
yes you are right for https://github.com/inmarelibero/gitignore-checker/issues/3#issuecomment-470515904, I still have to handle comments and lines beginning with `\#`

**Comment by inmarelibero** [comment]
implemented in https://github.com/inmarelibero/gitignore-checker/commit/c35c29788fc856a7e9964ca592130bb6a490bdbe
