### ISSUE TITLE
Rule cannot be created from comment

### ISSUE THREAD

**Issue by Endermanbugzjfc** [inmarelibero/gitignore-checker#9]
`Inmarelibero\GitIgnoreChecker\Exception\InvalidArgumentException: "Rule cannot be created from comment, "# This file is using the gitignore syntax, enjoy!" given."`
Tell me how can I even let it to not create rules from comment

**Comment by inmarelibero** [comment]
hi @Endermanbugzjfc can you paste the complete file you are using? does it contain only:
```
# This file is using the gitignore syntax, enjoy!
```
?

**Comment by Endermanbugzjfc** [comment]
```gitignore
# This file is using the gitignore syntax, enjoy!
# Specify filepatterns you want the backup file archiver to ignore.

backup-*-*-* *-*-*.*
PocketMine-MP.phar
bin/
*.lock
```
Never mind, I made it to remove all the comments before the check starts and it did worked.

**Comment by inmarelibero** [comment]
ok, thanks for reporting it anyway!
